### ISSUE TITLE
Add README to build the Oculus project

### ISSUE THREAD

**Issue by takuti** [Sushisushi-sandesu/UnityWebCamSample#3]
Plz write Import/build instruction :smiley:

**Comment by takuti** [comment]
なんか間違えてたくさんassignしちゃいましたごめんなさい :bow:

**Comment by natezzz** [comment]
Added Import/Build instruction. Please check if it works on your machines :)

**Comment by takuti** [comment]
Thx, now we can understand how to run this project. Btw, what are the requirements? e.g. unity sdk version. This information is important to integrate leap sdk. :innocent:

**Comment by natezzz** [comment]
According to the discussion on Monday, we will no longer be using Unity 5.2. Therefore this code will no longer be usable. We will rewrite the code for Unity 5.1.2 and update the repo very soon.

詳しくは金曜日のmtgで話そう~

**Comment by tomoasleep** [comment]
I want to read your new code before the next meeting on Friday.
Please update your new code before Friday :pray:

**Comment by natezzz** [comment]
No problem.
Actually the only difference is that the Dropdown menu is not provided in Unity 5.1.2 because it's a new API in Unity 5.2.
Also, the Canvas for displaying video taken by the webcam is removed since we will be using the default image provided by Leap Motion for now.
I'll try updating the code by Friday.
